config/routes.rb
Fishingtackle::Application.routes.draw do

  resources :users

  resources :helps

  resources :questions

  match "/answer/question/:question_id" => "helps#new"

  resources :suppliers

  resources :articles

  resources :sessions

  match "signup" => "users#new"
  match "login" => "sessions#new"
  match "signout" => "sessions#destroy"

  resources :admin_console

  match 'about' => 'footer#about'
  match 'connect' => 'footer#connect'
  post '/footer/create'
  match 'feedback' => 'footer#feedback'

  match "search" => "pages#search"

  root :to => 'pages#home'

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :content, :title

  validates :title, :presence => true, :length => {:maximum => 100}, :uniqueness => true
  validates :content, :presence => true, :length => {:maximum => 20000}

  belongs_to :user

  def self.all_by_created_time
    Article.order('created_at desc')
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_filter :signed_in_user,
                :only => [:new, :create, :edit, :update, :destroy]
  before_filter :correct_user, :only => [:edit, :update]
  before_filter :admin_user, :only => :destroy

  def initialize
    super
    @title = "Fishing tackle articles" + @title_tail
  end

  def index
    @articles = Article.all_by_created_time
  end

  def show
    @article = Article.find(params[:id])
    @title = @article.title + @title_tail
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(params[:article])
    @article.user = current_user

    if @article.save
      flash[:success] = "Article was successfully created."
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update_attributes(params[:article])
      flash[:success] = "Article was successfully updated."
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    Article.find(params[:id]).destroy
    flash[:success] = "Article destroyed."
    redirect_to articles_path
  end

  private

    def correct_user
      @article = Article.find(params[:id])
      redirect_to(root_path) unless current_user?(@article.user)
    end

end

app/helpers/articles_helper.rb
module ArticlesHelper

  def wrap(content)
    sanitize(raw(content.split.map { |s| wrap_long_string(s) }.join(' ')))
  end

  private

  def wrap_long_string(text, max_width = 30)
    zero_width_space = "&#8203;"
    regex = /.{1,#{max_width}}/
    (text.length < max_width) ? text :
        text.scan(regex).join(zero_width_space)
  end
end

app/views/articles/_article.html.erb
<div style="width: 100%;display: inline-block;margin-bottom: 5px;">
  <div style="width: 100%;background-color: #eee;border-bottom: 1px solid #bbb;border-right: 1px solid #bbb;margin-bottom: 5px;height: 30px;line-height: 30px;" class="rounded-corners">
    <b><a href="<%= article_path article %>" style="margin-left: 5px;"><%= article.title %></a></b>
  </div>
</div>

<div class="article-content">
  <%= wrap article.content %>
</div>
<div style="margin-bottom: 5px;text-align: right;">
  <%= render :partial => 'articles/article_maintenance', :locals => {:article => article} %>
</div>

app/views/articles/_article_maintenance.html.erb
<label style="display:inline;color: #ccc;">
  Posted by <%= article.user.name %> <%= time_ago_in_words article.created_at %> Ago&nbsp;
</label>
<a href="<%= article_path article %>">Show</a>&nbsp;
<% if current_user? article.user %>
    <a href="<%= edit_article_path article %>">Edit</a>&nbsp;
<% end %>
<% if (current_user and current_user.admin?) %>
    <%= link_to 'Destroy', article, confirm: 'Are you sure?', method: :delete %>
<% end %>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
    <% if @article.errors.any? %>
        <div id="error_explanation">
          <div class="alert alert-error">
            <%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:
          </div>

          <ul>
            <% @article.errors.full_messages.each do |msg| %>
                <li>* <%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :title, :class => 'inline-label' %>
      <%= f.text_field :title, :style => "width:735px;" %>
    </div>
    <div class="field">
      <%= f.cktext_area :content, :class => "cktext_area", :toolbar => "Basic" %>
    </div>
    <div class="actions" style="margin-top: 10px;">
      <%= f.submit :class => "btn" %>
    </div>
<% end %>

app/views/articles/edit.html.erb
<div style="margin-left: 30px;margin-right: 30px;margin-top: 10px;">
  <h1>Editing news</h1>
  <div class="common-line"></div>
  <%= render 'form' %>
</div>

app/views/articles/index.html.erb
<table>
  <tr>
    <td style='vertical-align:top;'>
      <div class="main-content">
        <h2>Fishing Tackle News</h2>
        <%= render @articles %>
      </div>
    </td>

    <td width='12px;'></td>

    <td style='vertical-align:top;'>
      <div class="side-bar">
        <div class="side-content">
          <%= render 'common/article_button' %>
        </div>
      </div>
    </td>
  </tr>
</table>

app/views/articles/new.html.erb
<div style="margin-left: 30px;margin-right: 30px;margin-top: 10px;">
  <h1>Add news</h1>
  <div class="common-line"></div>
  <%= render 'form' %>
</div>

app/views/articles/show.html.erb
<div class="main-content">
  <h3 style="text-align: center;"><%= @article.title %></h3>

  <p>
    <%= @article.content.html_safe %>
  </p>

  <p style="text-align: right;">
    <%= render :partial => 'articles/article_maintenance', :locals => {:article => @article} %>
  </p>
</div>

<div class="divide-dev"></div>

<div class="side-bar">
  <div class="side-content">
    <%= render 'common/article_button' %>
  </div>
  <div class="side-content" style="margin-top: 10px;">
    <%= render 'common/adsense' %>
  </div>
</div>