config/routes.rb
Fishingtackle::Application.routes.draw do

  resources :users

  resources :helps

  resources :questions

  match "/answer/question/:question_id" => "helps#new"

  resources :suppliers

  resources :articles

  resources :sessions

  match "signup" => "users#new"
  match "login" => "sessions#new"
  match "signout" => "sessions#destroy"

  resources :admin_console

  match 'about' => 'footer#about'
  match 'connect' => 'footer#connect'
  post '/footer/create'
  match 'feedback' => 'footer#feedback'

  match "search" => "pages#search"

  root :to => 'pages#home'

end

app/views/pages/home.html.erb
<table>
  <tr>
    <td style='vertical-align:top;'>
      <div class="main-content" style="display: block;">
        <h2><%= @articles_title %></h2>
        <% @articles.each do |article| %>
            <div class="common-line" style="margin-top: 3px;margin-bottom: 3px;"></div>
            <a href="<%= article_path article %>"><%= article.title %></a>
        <% end %>
        <div style="text-align: right;height: 30px;line-height: 30px;">
          <a href="<%= articles_path %>" style="font-size: 1.2em">More News >></a>
        </div>
      </div>

      <div class="main-content" style="display: block;margin-top: 10px;">
        <h2><%= @suppliers_title %></h2>
        <% @suppliers.each do |supplier| %>
            <div class="common-line" style="margin-top: 3px;margin-bottom: 3px;"></div>
            <a href="<%= supplier_path supplier %>"><%= supplier.name %></a>
        <% end %>
        <div style="text-align: right;height: 30px;line-height: 30px;">
          <a href="<%= suppliers_path %>" style="font-size: 1.2em">More Suppliers >></a>
        </div>
      </div>

      <div class="main-content" style="display: block;margin-top: 10px;">
        <h2><%= @questions_title %></h2>
        <% @questions.each do |question| %>
            <div class="common-line" style="margin-top: 3px;margin-bottom: 3px;"></div>
            <a href="<%= question_path question %>"><%= question.title %></a>
        <% end %>
        <div style="text-align: right;height: 30px;line-height: 30px;">
          <a href="<%= questions_path %>" style="font-size: 1.2em">More Questions >></a>
        </div>
      </div>
    </td>

    <td width='12px;'></td>

    <td style='vertical-align:top;'>

      <div class="side-bar">
        <div class="side-content">
          <%= render 'common/article_button' %>
        </div>
        <%#= render 'common/supplier_button' %>
        <%#= render 'common/question_button' %>
      </div>

      <!--<div class="side-content" style="margin-top: 10px;">-->
        <!--<%#= render 'common/adsense' %>-->
      <!--</div>-->
    </td>
  </tr>
</table>