config/routes.rb
Fishingtackle::Application.routes.draw do

  resources :users

  resources :helps

  resources :questions

  match "/answer/question/:question_id" => "helps#new"

  resources :suppliers

  resources :articles

  resources :sessions

  match "signup" => "users#new"
  match "login" => "sessions#new"
  match "signout" => "sessions#destroy"

  resources :admin_console

  match 'about' => 'footer#about'
  match 'connect' => 'footer#connect'
  post '/footer/create'
  match 'feedback' => 'footer#feedback'

  match "search" => "pages#search"

  root :to => 'pages#home'

end

app/views/common/_adsense.html.erb
<%= render 'common/adsense_real' %>

app/views/common/_adsense_real.html.erb
<script type="text/javascript"><!--
google_ad_client = "ca-pub-0209673531268166";
/* 渔具网首页小广告_A */
google_ad_slot = "0743414604";
google_ad_width = 200;
google_ad_height = 200;
//-->
</script>
<script type="text/javascript"
        src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>

app/views/common/_article_button.html.erb
<a href="<%= new_article_path %>" class="btn" style="color: #4d4d4d;display:block;width: 100px;margin-top: 10px;margin-bottom: 10px;margin-left: auto;margin-right: auto;">
  Add News
</a>

app/views/common/_disqus.html.erb
<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'fishingtackleheroku';

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<!--<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>-->
<!--<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a>-->

app/views/common/_question_button.html.erb
<a href="<%= new_question_path %>" class="btn" style="color: #4d4d4d;display:block;width: 100px;margin-top: 10px;margin-bottom: 10px;margin-left: auto;margin-right: auto;">
  Ask a question
</a>

app/views/common/_share_facebook.html.erb
<div style="display: block;width: 95px;">
  <!-- facebook -->
  <iframe src="//www.facebook.com/plugins/like.php?href=<%= request.url %>;send=false&amp;layout=button_count&amp;width=450&amp;show_faces=false&amp;action=like&amp;colorscheme=light&amp;font=arial&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:450px; height:21px;" allowTransparency="true"></iframe>
</div>

app/views/common/_share_gplus.html.erb
<div style="display: block;width: 95px;">
  <!-- google plus -->
  <!-- Place this tag where you want the +1 button to render -->
  <g:plusone size="medium"></g:plusone>
  <!-- Place this render call where appropriate -->
  <script type="text/javascript">
      (function() {
          var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
          po.src = 'https://apis.google.com/js/plusone.js';
          var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
      })();
  </script>
</div>

app/views/common/_share_twitter.html.erb
<div style="display: block;width: 95px;">
  <!-- twitter -->
  <%# ?text=<%= "#{request.url} #{@title}" %>
  <a href="https://twitter.com/share" class="twitter-share-button" data-via="andy_k_w">Tweet</a>
  <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
</div>

app/views/common/_supplier_button.html.erb
<a href="<%= new_supplier_path %>" class="btn" style="color: #4d4d4d;display:block;width: 100px;margin-top: 10px;margin-bottom: 10px;margin-left: auto;margin-right: auto;">
  Add a supplier
</a>