config/routes.rb
Fishingtackle::Application.routes.draw do

  resources :users

  resources :helps

  resources :questions

  match "/answer/question/:question_id" => "helps#new"

  resources :suppliers

  resources :articles

  resources :sessions

  match "signup" => "users#new"
  match "login" => "sessions#new"
  match "signout" => "sessions#destroy"

  resources :admin_console

  match 'about' => 'footer#about'
  match 'connect' => 'footer#connect'
  post '/footer/create'
  match 'feedback' => 'footer#feedback'

  match "search" => "pages#search"

  root :to => 'pages#home'

end

app/views/layouts/_footer.html.erb
<div class="footer">
  <div style="display: inline-block;vertical-align: top;">
    <!--© 2012 By <a href="https://twitter.com/#!/andy_k_w">@andy_k_w</a>-->
    <a href="/about" target="_blank">About</a> |
    <a href="/connect" target="_blank">Connect or Feedback</a> |
    <a href="https://twitter.com/#!/keatingwang" target="_blank">Follow Twitter</a> |
    <a href="http://www.weibo.com/keatingwang" target="_blank">Follow Weibo</a>
  </div>
  <div style="display: inline-block;float:right;text-align: right;vertical-align: top;">
    <!--<a href="<%#= root_path %>">About</a>&nbsp;&nbsp;-->
    <!--<a href="<%#= root_path %>">Contact</a>-->
    <!--outofclouds@gmail.com-->
    Copyright © 2012 All Rights Reserved
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="navbar  navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="<%= root_path %>" style="font-style: italic;">
        <!--<img src="/assets/starfish.jpg" alt="" />-->
        <b>Fishing Tackle</b>
      </a>
      <ul class="nav">
        <li id='nav-articles'>
          <a href="<%= articles_path %>">News</a>
        </li>
        <li id="nav-suppliers">
          <a href="<%= suppliers_path %>">Suppliers</a>
        </li>
        <li id="nav-questions">
          <a href="<%= questions_path %>">Questions & Help</a>
        </li>
      </ul>
      <ul class="nav pull-right">
        <% if sign_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account&nbsp;<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li>
                  <a href="<%= user_path current_user %>">Profile</a>
                </li>
                <li>
                  <a href="<%= edit_user_path current_user %>">Settings</a>
                </li>
                <li class="divider"></li>
                <li>
                  <a href="<%= signout_path %>">Sign out</a>
                </li>
              </ul>
            </li>
        <% else %>
            <li><a href="<%= signup_path %>">Sign Up</a></li>
            <li><a href="<%= login_path %>">Login</a></li>
        <% end %>
      </ul>
      <form class="navbar-search pull-left" action="<%= search_path %>">
        <input type="text" class="search-query" placeholder="Search" name="content">
      </form>
    </div>
  </div>
</div>
<script type="text/javascript">
    $(function () {
        $("#nav-<%= params[:controller] %>").addClass('active');
    })
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-31589198-1']);
      _gaq.push(['_trackPageview']);

      (function() {
          var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
          ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
          var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

  </script>


</head>
<body>

  <%= render 'layouts/header' %>

  <div class="content">
    <%= yield %>
  </div>

  <%= render 'layouts/footer' %>

  <!-- share -->
  <!--<div style="position: fixed;right: 1px; top: 300px;width: 100px;">-->
    <%#= render 'common/share_facebook' %>
    <%#= render 'common/share_twitter' %>
    <%#= render 'common/share_gplus' %>
  <!--</div>-->

</body>
</html>